### PR TITLE
Added hyper-cyberpunk plugin

### PR DESCRIPTION
**Pull request by manniefesto**

### CODE REVIEW

**Comment by timothyis** [comment]
Hi @manniefesto! Would you be able to make the gif twice as large so that it looks good on retina screens?

**Comment by manniefesto** [comment]
@timothyis All sorted :+1:

**Comment by timothyis** [comment]
Hi @manniefesto, would you mind classifying this as a theme instead?

**Comment by manniefesto** [comment]
@timothyis All done :)

**Pull request merged**
