### PR TITLE
Add hyper-quit to plugins

### PR DESCRIPTION
**Pull request by cblecker**

### CODE REVIEW

**Comment by timothyis** [comment]
Nice, thanks for the submission!

A few tiny requests:
1. Could you change the description to something easier to understand like `Quit Hyper on macOS when the last tab is closed`
2. The gif you recorded is too small and won't render well. Hyper Store is all about presentation. Would it be possible to re-record the gif at minimum 600x400 pixels (at double density). [Kap](getkap.co) will handle this for you if you record on a retina screen.
3. Could you perhaps show the macOS dock in your gif to show that the app has quit? e.g. show that the little dot underneath has gone. That was what made me realise what the plugin did initially.

After these, I'd be happy to merge your plugin! 

Let me know if you need help with the gif, I'm happy to help.

**Comment by cblecker** [comment]
I've updated the description. I've been having some problems with Kap and full screen recording in a VM (I can't do full screen recording with the dock of my main machine). If you're able to help with the gif, that would be amazing.

**Comment by timothyis** [comment]
Sorry for the delay! I'll get to this soon 🙏

**Comment by timothyis** [comment]
Sorry for the delay again! It looks like Hyper does this by default now, would you be able to elaborate on how this plugin helps?

I'm going to close this, for now, feel free to ping me if this has updated!

**Comment by cblecker** [comment]
@timothyis Unless I'm missing something, it doesn't actually do this on macOS still:
https://github.com/zeit/hyper/issues/939
https://github.com/zeit/hyper/issues/1561

**Comment by timothyis** [comment]
@cblecker I noticed those, but tried it myself yesterday and it worked.

**Comment by cblecker** [comment]
What version are you running? I just tried with 2.1.0-canary.2, and it doesn't work unless the plugin is installed. The window closes, but the app continues to run.

**Comment by cblecker** [comment]
@timothyis any update?

**Comment by cblecker** [comment]
thank you! 🎉

**Pull request merged**
