### PR TITLE
Add hyper-relaxed theme

### PR DESCRIPTION
**Pull request by mischah**
[hyper-relaxed](https://www.npmjs.com/package/hyper-relaxed)

hyper

### CODE REVIEW

**Comment by timothyis** [comment]
Hi @mischah, it seems the service you used to link the image is erroring out. Could you try and alternate version?

**Comment by mischah** [comment]
@timothyis Thanks.
Done. Resolved the merge conflict as well.

**Comment by mischah** [comment]
Hej, is there anything in addition I need to do to get this merged?

**Comment by timothyis** [comment]
Hi @mischah! I'm sorry for the delay on this 😓Would it be possible for the image to be shorter in height (there's a lot of content on that screenshot!) and also possibly make the screenshot @2x density? (so it looks nice on retina screens etc.). Then I'd be happy to merge! Also let me know if you need help taking that screenshot, I'd be happy to help

**Comment by racha999** [comment]
https://www.linkedin.com/in/racha999
เมื่อ 18 มิ.ย. 2018 07:09 "Timothy" <notifications@github.com> เขียนว่า:

**Comment by racha999** [comment]
เมื่อ 18 มิ.ย. 2018 07:09 "Timothy" <notifications@github.com> เขียนว่า:

**Pull request merged**
