### PR TITLE
Add hyper-named-css-colors theme and hyper-fading-scrollbar plugin

### PR DESCRIPTION
**Pull request by simonhaenisch**

### CODE REVIEW

**Comment by simonhaenisch** [comment]
Hey sorry, don't know what I did when I first made this PR but I must have been very tired... somehow I just copy-pasted a plugin entry (I think I had two tabs open and submitted the wrong one or sth 🤦🏻‍♂️).

Anyway, it's all updated now and I also added a screenshot that's more similar to the ones you already have.

<https://www.npmjs.com/package/hyper-named-css-colors>

Screenshot of Named CSS Colors Theme

**Comment by timothyis** [comment]
Hi! Thank you so much for the submission @simonhaenisch. 
Just a few requests from me:
1. Would you be able to make the screenshot and gif @2x density so they display nicely on retina screens etc. The Hyper Store is all about the look!
2. If possible could you show the plugin in the gif without the theme active. Just so users can see what's different to vanilla Hyper
Thank you 🙏

**Comment by simonhaenisch** [comment]
@timothyis done, please review 🤓

**Comment by simonhaenisch** [comment]
@timothyis is this gonna take another 2 months to be accepted?

**Comment by simonhaenisch** [comment]
@timothyis no idea why that deployment failed (it failed immediately)

**Pull request closed without merging**
