### PR TITLE
Add hyper-night-owl theme

### PR DESCRIPTION
**Pull request by pbomb**

### CODE REVIEW

**Comment by pbomb** [comment]
Is there anything I can help with to get this PR merged?

**Comment by timothyis** [comment]
Sorry for the delay @pbomb. I've been very busy recently. I'll set some time aside this weekend to merge or review the outstanding PRs we have

**Comment by timothyis** [comment]
@pbomb Sorry for the even further delay 😓
I'd love to merge you're PR, I just have one request though. Would you be able to provide the image at a @2x density so that it looks good on retina screens? The minimum width is 600px (which is 1200px when doubled for @2x density)
Thanks 🙏

**Comment by pbomb** [comment]
@timothyis I just pushed up a new image that is 1200x767. Let me know if you need anything else. Thanks!

**Comment by MAPESO** [comment]
@pbomb Thanks 😸👍

**Comment by pbomb** [comment]
@timothyis @MAPESO is this ready to be merged?

**Comment by timothyis** [comment]
Hi @pbomb, I'll review and probably merge this tomorrow. I need to make sure the JSON is formatted correctly, and that's all 🙏

**Comment by timothyis** [comment]
Actually, seems to work fine: https://hyper-site-kmyfuzancu.zeit.sh/plugins/hyper-night-owl

Will deploy tomorrow, but merge now!

**Comment by pbomb** [comment]
Great, thanks!

**Pull request merged**
