### PR TITLE
Add plugin `hyper-final-say`

### PR DESCRIPTION
**Pull request by amio**
https://www.npmjs.com/package/hyper-final-say

### CODE REVIEW

**Comment by timothyis** [comment]
Hi! Thanks for the submission! I'll test the plugin soon 🙏

**Comment by amio** [comment]
Basically what it does is re-assign configs (as the last one of plugins list), so it should support all configurations.

**Comment by timothyis** [comment]
I agree Hyper should have this built in. cc @chabou @juancampa

**Comment by chabou** [comment]
I don't think that user's configuration should have highest priority. It would break every theme imo.

**Pull request merged**
